---
- name: "RUST | Check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: "RUST | Download Installer"
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: "RUST | Install rust/cargo"
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: "RUST | Check what shell we are running"
  ansible.builtin.shell: cat /proc/$$/comm
  register: returned_shell

- name: "RUST | Add go binary path to ~/.zshrc"
  when: returned_shell.stdout.find('zsh') != -1
  lineinfile:
    path: '{{ ansible_user_dir }}/.zshrc'
    line: 'export PATH=$PATH:$HOME/.cargo/bin'
    create: true
    state: present

- name: "RUST | Source updated profile"
  when: returned_shell.stdout.find('zsh') != -1
  shell: . ~/.zshrc

- name: "RUST | Add go binary path to ~/.bashrc"
  when: returned_shell.stdout.find('bash') != -1
  lineinfile:
    path: '{{ ansible_user_dir }}/.bashrc'
    line: 'export PATH=$PATH:$HOME/.cargo/bin'
    create: true
    state: present

- name: "RUST | Source updated profile"
  when: returned_shell.stdout.find('bash') != -1
  shell: . ~/.bashrc