---
- name: "RUST | Check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: "RUST | Download Installer"
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: "RUST | Install rust/cargo"
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: "RUST | Add to $PATH."
  copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    content: "PATH=$PATH:$HOME/.cargo/bin'