---
# tasks file for oh_my_zsh
- name: OH_MY_ZSH | Install git Install Oh-my-zsh
  become: true
  ansible.builtin.apt:
    name: 
      - git
    state: present
 
- name: OH_MY_ZSH | Install ZSH
  become: true
  ansible.builtin.apt:
    name: 
      - zsh
    state: present

- name: OH_MY_ZSH | Install Powerline fonts
  become: true
  ansible.builtin.apt:
    name:
      - fonts-powerline
    state: present

- name: OH_MY_ZSH | Install ripgrep
  become: true
  ansible.builtin.apt:
    name: 
      - ripgrep
    state: present

- ansible.builtin.include_role:
    name: fzf

- ansible.builtin.include_role:
    name: tmux

- name: OH_MY_ZSH | Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
 
- name: OH_MY_ZSH | Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
 
- name: OH_MY_ZSH | Install zsh-completions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1
 
- name: OH_MY_ZSH | Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: OH_MY_ZSH | Gruvbox Theme
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme"
    dest: ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme

- name: OH_MY_ZSH | Change Prompt"
  ansible.builtin.shell:
    cmd: sed -i '/prompt_dir/{ n; s/'%~'/'%2~'/g }' ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme
  args:
    executable: /bin/bash

- name: "OH_MY_ZSH | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link
    force: true

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

