---
- name: "System | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    state: latest
    autoremove: true
    autoclean: true
  become: true

- name: "System | Install base packages"
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - sudo
      - neofetch
      - htop
    state: present
  become: true

- name: "System | Ensure group exists for current user"
  ansible.builtin.group:
    name: "{{ host_user }}"
    state: present
  become: true

- name: "System | Ensure user is in group {{ host_user }}"
  ansible.builtin.user:
    name: "{{ host_user }}"
    groups: "{{ host_user }}"
    append: true
  become: true
