---
- name: "FZF | Uninstall APT fzf"
  become: true
  ansible.builtin.apt:
    name: 
      - fzf
    state: absent


- name: "FZF | Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.fzf"
  notify: "Install FZF"
